import = [
  "~/.config/alacritty/baitong.toml"
]

live_config_reload = true

[font]
normal = { family = "DejaVuSansMono Nerd Font Mono" }
size = 12
builtin_box_drawing = true

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9
blur = true
option_as_alt = "Both"
dimensions = { columns = 200, lines = 60 }

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15
