alias reload!='. ~/.zshrc'
alias hidden-up='defaults write com.apple.finder AppleShowAllFiles -boolean true && killall Finder'
alias hidden-down='defaults delete com.apple.finder AppleShowAllFiles && killall Finder'
alias tags-create='ctags -a -e -f TAGS --tag-relative --exclude=vendor/bundle --exclude=.git --exclude=tmp --exclude=log --exclude=db -R app lib vendor test spec'
alias biq-production='ssh -t biq_production "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-staging='ssh -t biq_staging "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-development='ssh -t biq_development "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-demo='ssh -t brownbag@biq-demo.cloudapp.net -p 28820 "cd /home/brownbag/brownbag; /bin/bash -i"'
alias lj-staging='ssh -t lj_staging "cd /var/www/ladyjanes; /bin/bash -i"'
alias lj-production='ssh -t lj_production "cd /var/www/ladyjanes; /bin/bash -i"'
alias emacs-up='emacs --daemon'
alias emacs-down='emacsclient -e "(kill-emacs)"'
alias ew='emacsclient -c $@'
alias et='emacsclient -t $@'

