alias reload!='. ~/.zshrc'
alias hidden-up='defaults write com.apple.Finder AppleShowAllFiles YES'
alias hidden-down='defaults write com.apple.Finder AppleShowAllFiles NO'
alias tags-create='ctags -e -R --exclude=db --exclude=log --exclude=tmp --exclude=test --exclude=.git --exclude=public --exclude=vendor'
alias biq-production='ssh -t biq_production "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-staging='ssh -t biq_staging "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-development='ssh -t biq_development "cd /home/brownbag/brownbag; /bin/bash -i"'
alias biq-demo='ssh -t brownbag@biq-demo.cloudapp.net -p 28820 "cd /home/brownbag/brownbag; /bin/bash -i"'
alias lj-staging='ssh -t lj_staging "cd /var/www/ladyjanes; /bin/bash -i"'

